//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "ДатаЗаказа as \'Дата заказа\'",
            "ТипОплаты as \'Тип оплаты\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "ГорячиеНапитки", "ГорячиеНапиткиE", true, "", "Горячие напитки", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ЗаказE", "Еда", "ЕдаE", true, "", "Еда", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "ДатаЗаказа as \'Дата заказа\'",
            "ТипОплаты as \'Тип оплаты\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private string fДатаЗаказа;
        
        private IIS.Novyjj_proekt.Оплата fТипОплаты;
        
        private IIS.Novyjj_proekt.DetailArrayOfГорячиеНапитки fГорячиеНапитки;
        
        private IIS.Novyjj_proekt.DetailArrayOfЕда fЕда;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// ДатаЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.ДатаЗаказа Get start)
                string result = this.fДатаЗаказа;
                // *** Start programmer edit section *** (Заказ.ДатаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.ДатаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.ДатаЗаказа Set start)
                this.fДатаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.ДатаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.ДатаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ТипОплаты CustomAttributes)
        public virtual IIS.Novyjj_proekt.Оплата ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ТипОплаты Get start)

                // *** End programmer edit section *** (Заказ.ТипОплаты Get start)
                IIS.Novyjj_proekt.Оплата result = this.fТипОплаты;
                // *** Start programmer edit section *** (Заказ.ТипОплаты Get end)

                // *** End programmer edit section *** (Заказ.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ТипОплаты Set start)

                // *** End programmer edit section *** (Заказ.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Заказ.ТипОплаты Set end)

                // *** End programmer edit section *** (Заказ.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ГорячиеНапитки CustomAttributes)

        // *** End programmer edit section *** (Заказ.ГорячиеНапитки CustomAttributes)
        public virtual IIS.Novyjj_proekt.DetailArrayOfГорячиеНапитки ГорячиеНапитки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ГорячиеНапитки Get start)

                // *** End programmer edit section *** (Заказ.ГорячиеНапитки Get start)
                if ((this.fГорячиеНапитки == null))
                {
                    this.fГорячиеНапитки = new IIS.Novyjj_proekt.DetailArrayOfГорячиеНапитки(this);
                }
                IIS.Novyjj_proekt.DetailArrayOfГорячиеНапитки result = this.fГорячиеНапитки;
                // *** Start programmer edit section *** (Заказ.ГорячиеНапитки Get end)

                // *** End programmer edit section *** (Заказ.ГорячиеНапитки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ГорячиеНапитки Set start)

                // *** End programmer edit section *** (Заказ.ГорячиеНапитки Set start)
                this.fГорячиеНапитки = value;
                // *** Start programmer edit section *** (Заказ.ГорячиеНапитки Set end)

                // *** End programmer edit section *** (Заказ.ГорячиеНапитки Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Еда CustomAttributes)

        // *** End programmer edit section *** (Заказ.Еда CustomAttributes)
        public virtual IIS.Novyjj_proekt.DetailArrayOfЕда Еда
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Еда Get start)

                // *** End programmer edit section *** (Заказ.Еда Get start)
                if ((this.fЕда == null))
                {
                    this.fЕда = new IIS.Novyjj_proekt.DetailArrayOfЕда(this);
                }
                IIS.Novyjj_proekt.DetailArrayOfЕда result = this.fЕда;
                // *** Start programmer edit section *** (Заказ.Еда Get end)

                // *** End programmer edit section *** (Заказ.Еда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Еда Set start)

                // *** End programmer edit section *** (Заказ.Еда Set start)
                this.fЕда = value;
                // *** Start programmer edit section *** (Заказ.Еда Set end)

                // *** End programmer edit section *** (Заказ.Еда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Novyjj_proekt.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Novyjj_proekt.Заказ));
                }
            }
        }
    }
}
