//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    public enum Оплата
    {
        
        // *** Start programmer edit section *** (Оплата.Безналичный CustomAttributes)

        // *** End programmer edit section *** (Оплата.Безналичный CustomAttributes)
        [Caption("Безналичный")]
        Безналичный,
        
        // *** Start programmer edit section *** (Оплата.Наличный CustomAttributes)

        // *** End programmer edit section *** (Оплата.Наличный CustomAttributes)
        [Caption("Наличный")]
        Наличный,
    }
}
