//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Составы.
    /// </summary>
    // *** Start programmer edit section *** (Составы CustomAttributes)

    // *** End programmer edit section *** (Составы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставыE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("СоставыL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Составы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Составы CustomMembers)

        // *** End programmer edit section *** (Составы CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Составы.Наименование CustomAttributes)

        // *** End programmer edit section *** (Составы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Составы.Наименование Get start)

                // *** End programmer edit section *** (Составы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Составы.Наименование Get end)

                // *** End programmer edit section *** (Составы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Составы.Наименование Set start)

                // *** End programmer edit section *** (Составы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Составы.Наименование Set end)

                // *** End programmer edit section *** (Составы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставыE", typeof(IIS.Novyjj_proekt.Составы));
                }
            }
            
            /// <summary>
            /// "СоставыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставыL", typeof(IIS.Novyjj_proekt.Составы));
                }
            }
        }
    }
}
